# Generated by Django 3.1.7 on 2021-02-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbox', '0003_gamedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
