# Generated by Django 3.1.7 on 2021-03-03 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbox', '0007_auto_20210302_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
        migrations.AddField(
            model_name='game',
            name='wishlist_users',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
