# Generated by Django 3.1.7 on 2021-03-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbox', '0008_auto_20210303_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='on_gamepass',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
