# Generated by Django 3.1.7 on 2021-03-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbox', '0009_game_on_gamepass'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='days_left_on_sale',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='page_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
