# Generated by Django 3.1.7 on 2021-03-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbox', '0010_auto_20210309_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='regular_price_available',
            field=models.BooleanField(default=False),
        ),
    ]
