# Generated by Django 3.1.7 on 2021-03-09 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xbox', '0011_auto_20210309_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='page_discount',
            new_name='discount',
        ),
    ]
